modLoader="javafml"
loaderVersion="[0,)"
license="MIT"
issueTrackerURL="https://github.com/BlueMap-Minecraft/BlueMap/issues"

[[mods]]
modId="bluemap"
version="${version}"
displayName="BlueMap"
displayURL="https://github.com/BlueMap-Minecraft/BlueMap"
authors="Blue (TBlueF, Lukas Rieger)"
description="A 3d-map of your Minecraft worlds view-able in your browser using three.js (WebGL)"

[[dependencies.bluemap]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="SERVER"
[[dependencies.bluemap]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="SERVER"
