blank_issues_enabled: false
contact_links:
  - name: Suggestion or Question
    url: https://bluecolo.red/map-discord
    about: You have a suggestion, a question or a problem that is not a bug? Please use our discord-server for this! :)
