##                          ##
##         BlueMap          ##
##     Webserver-Config     ##
##                          ##

# With this setting you can disable the integrated webserver.
# This is useful if you want to only render the map data for later use, or if you setup your own webserver.
# Default is true
enabled: true

# The webroot that the server will host to the web.
# Usually this should be set to the same directory like in the webapp.conf!
# Default is "bluemap/web"
webroot: "${webroot}"

# The port that the webserver listens to.
# Default is 8100
port: 8100

# Whether to use Server-Sent Events (SSE) for pushing tile and marker-updates to the connected clients.
# Default is true
sse-enabled: true

# Additional headers the webserver should include in the responses it sends.
# Default is none
additional-headers: {
  "Cache-Control": "public, max-age=86400"
  # "Content-Security-Policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; object-src 'none';"
  "X-Frame-Options": "SAMEORIGIN"
  "X-Content-Type-Options": "nosniff"
  "Referrer-Policy": "strict-origin-when-cross-origin"
  "Permissions-Policy": """
    accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(),
    display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(),
    execution-while-out-of-viewport=(), fullscreen=(self), geolocation=(), gyroscope=(), keyboard-map=(),
    magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(),
    publickey-credentials-get=(), screen-wake-lock=(self), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()
  """
}

# Config-section for webserver activity logging:
log: {
  # The file where all the webserver activity will be logged to.
  # Comment out to disable the logging completely.
  # Java String formatting syntax can be used to add timestamps, see: https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html
  # Default is no logging.
  file: "${logfile}"
  #file: "${logfile-with-time}"

  # Whether the logger should append to an existing file, or overwrite it.
  # Default is false (overwrite the file).
  append: false

  # The format of the webserver activity logs.
  # The syntax is the Java String formatting syntax, see: https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html
  # Possible Arguments:                                                    | Example output
  #  1 - the source address (ignoring any xff headers).                    | 10.10.10.10
  #  2 - the source address (using the (leftmost) xff header if provided). | 88.66.44.22
  #  3 - the http method of the request.                                   | GET
  #  4 - the full request address.                                         | /assets/file.png 
  #  5 - the protocol version of the request.                              | HTTP/1.1
  #  6 - the status code of the response.                                  | 200
  #  7 - the status message of the response.                               | OK
  # Default is "%1$s \"%3$s %4$s %5$s\" %6$s %7$s"                         | 10.10.10.10 "GET /assets/file.png HTTP/1.1" 200 OK
  format: "%1$s \"%3$s %4$s %5$s\" %6$s %7$s"
}
