modLoader="javafml"
loaderVersion="[${loader_version},)"
license="MIT"

[[mods]]
modId="bluemap"
version="${version}"
displayName="BlueMap"
description='''A 3d-map of your Minecraft worlds view-able in your browser using three.js (WebGL)'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.bluemap]]
    modId="neoforge"
    mandatory=true
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bluemap]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
