##                          ##
##         BlueMap          ##
##      Storage-Config      ##
##                          ##

# The storage-type of this storage.
# Depending on this setting, different config entries are allowed/expected in this config file.
# Don't change this value! If you want a different storage-type, check out the other example configs.
storage-type: sqlite

# The location of the SQLite database file.
# The default is: "bluemap/map.db"
file-location: "bluemap/map.db"

# The PRAGMA commands to run on initialization.
# Find PRAGMA command documentation at https://sqlite.org/pragma.html
# Some commands may improve render performance, hurt render performance, introduce possibly of corruption, use more RAM, etc.
# Add/change commands cautiously!
pragma-commands: [
  "journal_mode = WAL"
  "journal_size_limit = 268435456"
#  "cache_size = -65536" # Will use more RAM, but otherwise generally improves read performance when multiple people are browsing the map.
#  "synchronous = NORMAL" # ONLY SAFE TO USE WITH WAL! Otherwise improves write performance while rendering.
]

# This can be used to load a custom JDBC-Driver from a .jar file.
# E.g. if your runtime environment is not already providing an SQLite driver,
# you could download the SQLite JDBC-Connector from https://github.com/xerial/sqlite-jdbc/releases/
# If you set this value, you HAVE TO set the correct driver-class name below.
# Place it in the './bluemap' folder and use it like this:
#driver-jar: "bluemap/sqlite-jdbc-3.51.2.0.jar"

# This is the driver-class that BlueMap will try to load and use.
# Check the documentation of the driver you are using if you don't know this.
# Leaving this commented out means that BlueMap automatically tries to find a suitable driver in your classpath.
# If you added a custom driver-jar value above, you HAVE TO set the correct class name here.
#driver-class: "org.sqlite.JDBC"

# The compression type that BlueMap will use to compress generated map data.
# Available compression types are:
#  - gzip
#  - zstd
#  - deflate
#  - none
# The default is: gzip
compression: gzip
