##                          ##
##         BlueMap          ##
##      Storage-Config      ##
##                          ##

# The storage-type of this storage.
# Depending on this setting, different config entries are allowed/expected in this config file.
# Don't change this value! If you want a different storage-type, check out the other example configs.
storage-type: sqlite

# The JDBC-Connection URL that is used to connect to the database.
# The format for this URL is usually something like: jdbc:[driver]://[host]:[port]/[database]
# The exact format of the URL is determined by the JDBC-Driver you are using.
connection-url: "jdbc:sqlite:file:bluemap/map.db"

# The PRAGMA commands to run on the inital connection.
# Find PRAGMA commands at https://sqlite.org/pragma.html/
pragma-commands:
  - "journal_mode = WAL"
  - "cache_size = -20000"
  - "synchronous = NORMAL"

# This can be used to load a custom JDBC-Driver from a .jar file.
# E.g. if your runtime environment is not already providing an SQLite driver,
# you could download the SQLite JDBC-Connector from https://github.com/xerial/sqlite-jdbc/releases/
# If you set this value, you HAVE TO set the correct driver-class name below.
# Place it in the './bluemap' folder and use it like this:
#driver-jar: "bluemap/sqlite-jdbc-2.51.2.0"

# This is the driver-class that BlueMap will try to load and use.
# Check the documentation of the driver you are using if you don't know this.
# Leaving this commented out means that BlueMap automatically tries to find a suitable driver in your classpath.
# If you added a custom driver-jar value above, you HAVE TO set the correct class name here.
#driver-class: "org.sqlite.JDBC"

# The compression type that BlueMap will use to compress generated map data.
# Available compression types are:
#  - gzip
#  - zstd
#  - deflate
#  - none
# The default is: gzip
compression: gzip
